AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CI CD Version 1 N.Virginia

Parameters:
  MyEnvironment:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production
      - dr
    Description: Environment of this stack of resources

Mappings:
  ResourcesName:
    staging:
      funcName: MyLambda-staging
    production:
      funcName: MyLambda-production
    dr:
      funcName: MyLambda-dr

Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !FindInMap [ResourcesName, !Ref MyEnvironment, funcName]
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lambda
      Description: 'Lambda function for Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::899789784021:role/cicd-v1-lambda-role'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
          MODE: !Ref MyEnvironment
